apiVersion: v1
kind: Service
metadata:
  name: vprodb                  # based on the application.properties file for our application
spec:
  ports:
    - port: 3306                # port based on application.properties file
      targetPort: vprodb-port   # name of the port defined in db Deployment definition file
      protocol: TCP
  selector:
    app: vprodb                 # label of the db pod
  type: ClusterIP