apiVersion: v1
kind: Service
metadata:
  name: vpromq01                   # based on the application.properties file for our application
spec:
  ports:
    - port: 15672                  # port based on application.properties file
      targetPort: vpromq01-port    # name of the port defined in rabbitmq Deployment definition file
      protocol: TCP
  selector:
    app: vpromq01                  # label of the rabbitmq pod
  type: ClusterIP