apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromq01
  labels:
    app: vpromq01
spec:
  selector:
    matchLabels:
      app: vpromq01
  replicas: 1
  template:                               # pod info
    metadata:
      labels:
        app: vpromq01                     # label of the pod
    spec:
      containers:
        - name: vpromq01
          image: rabbitmq                 # official image from Docker Hub, not customized
          ports:
            - name: vpromq01-port
              containerPort: 15672        # port exposed in the memcached image
          # set env var for rabbitmq user and password
          env:
            - name: RABBITMQ_DEFAULT_PASS # this var is from official doc of rabbitmq image on Docker Hub
              valueFrom:
                secretKeyRef:
                  name: app-secret        # name of the secret
                  key: rmq-pass
            - name: RABBITMQ_DEFAULT_USER
              value: guest
